Select Comments__c,
Contact__c,
Date_of_Encounter__c,
Date_of_Scheduled_Visit__c,
Id,
Initiation_of_Encounter__c,
Interested_in_Signin_Session__c,
Length_of_Retention_Activity__c,
Name,
Other_Advertisement_Details__c,
Other_Details__c,
Other_Tech_Assist__c,
Phone_Call_Outcome__c,
Preferred_Time_for_Signin_Session__c,
Program_Reminder__c,
Reach_out_Community__c,
Reach_out_Participant__c,
Remember_Enrolling__c,
Retention_Activities__c,
Retention_Journey__c,
Retention_Method__c,
Retention_Site__c,
Staff_UNI__c,
Tech_Assistance__c
FROM Retention_Engagement__c
WHERE (CreatedById = '{}' or CreatedById = '{}' or CreatedById = '{}')