SELECT [Id]
      ,[Contact__c]
      ,[AccountId]
      ,[HP_Participant_Status__c]
      ,[HP_General_Consent_Status__c]
      ,[HP_General_Consent_Date__c]
      ,[HP_EHR_Consent_Status__c]
      ,[HP_EHR_Consent_Date__c]
      ,[HP_Withdrawal_Date__c]
      ,[HP_Withdrawal_Status__c]
      ,[HP_Basics_PPI_Survey_Completion_Date__c]
      ,[HP_Health_PPI_Survey_Completion_Date__c]
      ,[HP_Lifestyle_PPI_Survey_Completion_Date__c]
      ,[HP_Hist_PPI_Survey_Completion_Date__c]
      ,[HP_Meds_PPI_Survey_Completion_Date__c]
      ,[HP_Family_PPI_Survey_Completion_Date__c]
      ,[HP_Access_PPI_Survey_Completion_Date__c]
      ,[HP_Physical_Measurements_Completion_Date__c]
      ,[HP_Samples_for_DNA_Received__c]
      ,[HP_8_mL_SST_Collection_Date__c]
      ,[HP_8_mL_PST_Collection_Date__c]
      ,[HP_4_mL_Na_Hep_Collection_Date__c]
      ,[HP_4_mL_EDTA_Collection_Date__c]
      ,[HP_1st_10_mL_EDTA_Collection_Date__c]
      ,[HP_2nd_10_mL_EDTA_Collection_Date__c]
      ,[HP_Saliva_Collection_Date__c]
      ,[HP_Urine_10_ml_Collection_Date__c]
      ,[HP_2_mL_EDTA_Collection_Date__c]
      ,[HP_Cell_Free_DNA_Collection_Date__c]
      ,[HP_Paxgene_RNA_Collection_Date__c]
      ,[HP_Urine_90_ml_Collection_Date__c]
  FROM [aou_sf].[dbo].[v2_sf_journey_update_json]
  WHERE [HP_Withdrawal_Status__c] = 0